apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-nodejs
    app.kubernetes.io/part-of: local-transit
  name: 1-nodejs
  namespace: shbose
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: 1-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: 1-nodejs
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:shbose-1-nodejs
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3000
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
status: {}
