apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-nodejs
    app.kubernetes.io/part-of: local-transit
  name: 1-nodejs
  namespace: shbose
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: 1-nodejs
    weight: 100
status: {}
