apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-nodejs
    app.kubernetes.io/part-of: local-transit
  name: 1-nodejs
  namespace: shbose
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: 1-nodejs
status:
  loadBalancer: {}
