apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: good-old-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: good-old-quarkus
    app.kubernetes.io/part-of: local-transit
  name: good-old-quarkus
  namespace: shbose
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: good-old-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: good-old-quarkus
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:a3ebfdaa5e8eac2d3e8c7c8107e3af0b60c49c145c58294c499c56eda6b43e66
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 170m
            memory: 200Mi
status: {}
