apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: good-old-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: good-old-quarkus
    app.kubernetes.io/part-of: local-transit
  name: good-old-quarkus
  namespace: shbose
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: good-old-quarkus
    weight: 100
status: {}
