apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: good-old-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: good-old-quarkus
    app.kubernetes.io/part-of: local-transit
  name: good-old-quarkus
  namespace: shbose
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: good-old-quarkus
status:
  loadBalancer: {}
